[general]
import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[window]
opacity = 1
padding = { x = 2, y = 2 }
decorations = "Full"
dimensions = { columns = 80, lines = 24 }

[font]
normal.family = "IosBerkMono"
bold.family = "IosBerkMono"
bold.style = "Medium"
#  size = 12
offset.y = -2

[selection]
save_to_clipboard = false

[cursor.style]
blinking = "Off"

[mouse]
bindings = [
  { mouse = "Right", action = "Copy" }
]

# [terminal.shell]
# program = "/usr/bin/tmux"
# args = ["new-session", "-A", "-D"]

